server:
  port: 6565
  
spring:
  application:
    name: tour-agent-api
  h2:
    console:
      enabled: true
      path: /h2-console
      #settings:
        #trace: false
        #web-allow-others: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - "*"
    jmx:
      exposure:
        include:
        - "*"
        
info:
  app:
    name:@project.name@
    version:@project.version@
    encoding:@project.build.sourceEncoding@
  java:
      version:@java.version@

logging:
  level:
    '[org.springframework.security]': trace    
    
    
security:
  enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka   
       
