spring:
  application:
    name: api-gateway
 
zuul:
  routes:
    review-service:
      path: /review-service/**
      service-id: review-service

review-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:5858/,http://localhost:5959/   
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"    
