spring:
  application:
    name: customer-service
server:
  port: 5454

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka
