spring:
  application:
    name: invoice-service
  profiles:
  - dev
server:
  port: 5858
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
          

---

spring:
  application:
    name: invoice-service
  profiles:
  - prod
server:
  port: 5959
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka